### ISSUE TITLE
Update cookbook to use new API for latest and latest-esr

### ISSUE THREAD

**Issue by rhass** [rapid7-cookbooks/firefox_package#7]
Mozilla recently removed the files from the latest and latest-esr directories and have since replaced them with an API which returns an HTML href link to the path of respective files.

They have documented this API here:
https://download-installer.cdn.mozilla.net/pub/firefox/releases/latest-esr/README.txt 

This being said, this only applies to the latest and latest-esr versions. Named versions, such as '42.0.1' do not work with this API at this time and as such we will need to continue xpath parsing to identify those particular releases.

**Comment by cdoughty-r7** [comment]
This is now resolved:
https://github.com/rapid7/chef-firefox-package
